#include "StaticEventSource.h"

StaticEventSource::StaticEventSource() : currentIndex(0) {
    records = {
        {RecordType::Play, PlayInfo{1, 0, "duraj001", "7/F7D"}},
        {RecordType::Play, PlayInfo{1, 0, "dever001", "W"}},
        {RecordType::Play, PlayInfo{1, 0, "brega001", "S7/L78D+.1-2"}},
        {RecordType::Play, PlayInfo{1, 0, "refsr001", "K"}},
        {RecordType::Play, PlayInfo{1, 0, "stort001", "K"}},
        {RecordType::Play, PlayInfo{1, 1, "westj002", "S8/G6M"}},
        {RecordType::Play, PlayInfo{1, 1, "rutsa001", "S7/L7S.1-2"}},
        {RecordType::Play, PlayInfo{1, 1, "oneit001", "S7/G56.2-H;1-2"}},
        {RecordType::Play, PlayInfo{1, 1, "mounr001", "S7/L7LS.2-H;1-3(E7);B-2"}},
        {RecordType::Play, PlayInfo{1, 1, "kjerh001", "K"}},
        {RecordType::Play, PlayInfo{1, 1, "laurr001", "K"}},
        {RecordType::Play, PlayInfo{1, 1, "mullc002", "D8/L8D.3-H;2-H"}},
        {RecordType::Play, PlayInfo{1, 1, "uriar001", "K"}},
        {RecordType::Play, PlayInfo{2, 0, "campk002", "W"}},
        {RecordType::Play, PlayInfo{2, 0, "gonzr003", "S7/G56.1-2"}},
        {RecordType::Play, PlayInfo{2, 0, "wongc001", "K"}},
        {RecordType::Play, PlayInfo{2, 0, "rafac001", "K"}},
        {RecordType::Play, PlayInfo{2, 0, "duraj001", "T8/F78XD+.2-H;1-H"}},
        {RecordType::Play, PlayInfo{2, 0, "dever001", "K"}},
        {RecordType::Play, PlayInfo{2, 1, "hollj003", "S8/G6+"}},
        {RecordType::Play, PlayInfo{2, 1, "westj002", "CS2(24)"}},
        {RecordType::Comment, "$Orioles challenged (tag play), call on the field was upheld."},
        {RecordType::Play, PlayInfo{2, 1, "westj002", "W"}},
        {RecordType::Play, PlayInfo{2, 1, "rutsa001", "46(1)3/GDP/G4"}},
        {RecordType::Play, PlayInfo{3, 0, "brega001", "K"}},
        {RecordType::Play, PlayInfo{3, 0, "refsr001", "S7/L78"}},
        {RecordType::Play, PlayInfo{3, 0, "stort001", "S9/L9LS.1-3;B-2(E9/TH)"}},
        {RecordType::Play, PlayInfo{3, 0, "campk002", "43/G4MD.3-H;2-3"}},
        {RecordType::Play, PlayInfo{3, 0, "gonzr003", "K"}},
        {RecordType::Play, PlayInfo{3, 1, "oneit001", "S9/F9LS"}},
        {RecordType::Play, PlayInfo{3, 1, "mounr001", "W.1-2"}},
        {RecordType::Play, PlayInfo{3, 1, "kjerh001", "K"}},
        {RecordType::Play, PlayInfo{3, 1, "laurr001", "64(1)3/GDP/G6"}},
        {RecordType::Play, PlayInfo{4, 0, "wongc001", "13/G15"}},
        {RecordType::Play, PlayInfo{4, 0, "rafac001", "53/G5S"}},
        {RecordType::Play, PlayInfo{4, 0, "duraj001", "43/G34D"}},
        {RecordType::Play, PlayInfo{4, 1, "mullc002", "4/P4D"}},
        {RecordType::Play, PlayInfo{4, 1, "uriar001", "S67/G56"}},
        {RecordType::Play, PlayInfo{4, 1, "hollj003", "16(1)3/GDP/G1S"}},
        {RecordType::Play, PlayInfo{5, 0, "dever001", "K"}},
        {RecordType::Play, PlayInfo{5, 0, "brega001", "NP"}},
        {RecordType::Substitution, SubstitutionInfo{"bowmm001", "Matt Bowman", 1, 0, 1}},
        {RecordType::Play, PlayInfo{5, 0, "brega001", "8/F8"}},
        {RecordType::Play, PlayInfo{5, 0, "refsr001", "S7/G56"}},
        {RecordType::Play, PlayInfo{5, 0, "stort001", "SB2"}},
        {RecordType::Play, PlayInfo{5, 0, "stort001", "K"}},
        {RecordType::Play, PlayInfo{5, 1, "westj002", "NP"}},
        {RecordType::Substitution, SubstitutionInfo{"whitg002", "Garrett Whitlock", 0, 0, 1}},
        {RecordType::Play, PlayInfo{5, 1, "westj002", "53/G56"}},
        {RecordType::Play, PlayInfo{5, 1, "rutsa001", "K"}},
        {RecordType::Play, PlayInfo{5, 1, "oneit001", "D8/L89XD+"}},
        {RecordType::Play, PlayInfo{5, 1, "mounr001", "9/F9D"}},
        {RecordType::Play, PlayInfo{6, 0, "campk002", "NP"}},
        {RecordType::Substitution, SubstitutionInfo{"domis001", "Seranthony Dominguez", 1, 0, 1}},
        {RecordType::Play, PlayInfo{6, 0, "campk002", "K"}},
        {RecordType::Play, PlayInfo{6, 0, "gonzr003", "9/F89"}},
        {RecordType::Play, PlayInfo{6, 0, "wongc001", "4/L4D"}},
        {RecordType::Play, PlayInfo{6, 1, "kjerh001", "5/P56D"}},
        {RecordType::Play, PlayInfo{6, 1, "laurr001", "NP"}},
        {RecordType::Substitution, SubstitutionInfo{"carld002", "Dylan Carlson", 1, 6, 11}},
        {RecordType::Play, PlayInfo{6, 1, "carld002", "K"}},
        {RecordType::Play, PlayInfo{6, 1, "mullc002", "31/G34"}},
        {RecordType::Play, PlayInfo{7, 0, "rafac001", "NP"}},
        {RecordType::Substitution, SubstitutionInfo{"carld002", "Dylan Carlson", 1, 6, 9}},
        {RecordType::Play, PlayInfo{7, 0, "rafac001", "NP"}},
        {RecordType::Substitution, SubstitutionInfo{"akink001", "Keegan Akin", 1, 0, 1}},
        {RecordType::Play, PlayInfo{7, 0, "rafac001", "9/F9LD"}},
        {RecordType::Play, PlayInfo{7, 0, "duraj001", "K"}},
        {RecordType::Play, PlayInfo{7, 0, "dever001", "K"}},
        {RecordType::Play, PlayInfo{7, 1, "uriar001", "NP"}},
        {RecordType::Substitution, SubstitutionInfo{"weisg001", "Greg Weissert", 0, 0, 1}},
        {RecordType::Play, PlayInfo{7, 1, "uriar001", "S7/L7LS"}},
        {RecordType::Play, PlayInfo{7, 1, "hollj003", "K"}},
        {RecordType::Play, PlayInfo{7, 1, "westj002", "9/L9D"}},
        {RecordType::Play, PlayInfo{7, 1, "rutsa001", "9/F9LS"}},
        {RecordType::Play, PlayInfo{8, 0, "brega001", "NP"}},
        {RecordType::Substitution, SubstitutionInfo{"canoy001", "Yennier Cano", 1, 0, 1}},
        {RecordType::Play, PlayInfo{8, 0, "brega001", "63/G6"}},
        {RecordType::Play, PlayInfo{8, 0, "refsr001", "NP"}},
        {RecordType::Substitution, SubstitutionInfo{"abrew002", "Wilyer Abreu", 0, 4, 11}},
        {RecordType::Play, PlayInfo{8, 0, "abrew002", "13/G4MS"}},
        {RecordType::Play, PlayInfo{8, 0, "stort001", "K"}},
        {RecordType::Play, PlayInfo{8, 1, "oneit001", "NP"}},
        {RecordType::Substitution, SubstitutionInfo{"abrew002", "Wilyer Abreu", 0, 4, 9}},
        {RecordType::Play, PlayInfo{8, 1, "oneit001", "NP"}},
        {RecordType::Substitution, SubstitutionInfo{"slatj002", "Justin Slaten", 0, 0, 1}},
        {RecordType::Play, PlayInfo{8, 1, "oneit001", "S9/F89"}},
        {RecordType::Play, PlayInfo{8, 1, "mounr001", "S5/G6.1-3(E5/TH);B-2"}},
        {RecordType::Play, PlayInfo{8, 1, "kjerh001", "S7/L7S.3-H;2-3"}},
        {RecordType::Play, PlayInfo{8, 1, "carld002", "NP"}},
        {RecordType::Substitution, SubstitutionInfo{"matej003", "Jorge Mateo", 1, 5, 12}},
        {RecordType::Play, PlayInfo{8, 1, "carld002", "SB2"}},
        {RecordType::Play, PlayInfo{8, 1, "carld002", "W"}},
        {RecordType::Play, PlayInfo{8, 1, "mullc002", "NP"}},
        {RecordType::Substitution, SubstitutionInfo{"crisc002", "Cooper Criswell", 0, 0, 1}},
        {RecordType::Play, PlayInfo{8, 1, "mullc002", "S18/G4M.3-H;2-H;1-2"}},
        {RecordType::Play, PlayInfo{8, 1, "uriar001", "54(1)/FO/G6.2-3;B-1"}},
        {RecordType::Comment, "$Umpire reviewed (play at 1st), call on the field was overturned."},
        {RecordType::Play, PlayInfo{8, 1, "hollj003", "S7/L7S.3-H;1-2"}},
        {RecordType::Play, PlayInfo{8, 1, "westj002", "4(1)/FO/G4M.2-3;B-1"}},
        {RecordType::Play, PlayInfo{8, 1, "rutsa001", "4/L34D"}},
        {RecordType::Play, PlayInfo{9, 0, "campk002", "NP"}},
        {RecordType::Substitution, SubstitutionInfo{"bautf001", "Felix Bautista", 1, 0, 1}},
        {RecordType::Play, PlayInfo{9, 0, "campk002", "W"}},
        {RecordType::Play, PlayInfo{9, 0, "gonzr003", "WP.1-2"}},
        {RecordType::Play, PlayInfo{9, 0, "gonzr003", "D7/L7LD+.2-H"}},
        {RecordType::Play, PlayInfo{9, 0, "wongc001", "63/G6"}},
        {RecordType::Play, PlayInfo{9, 0, "rafac001", "NP"}},
        {RecordType::Substitution, SubstitutionInfo{"casat001", "Triston Casas", 0, 9, 11}},
        {RecordType::Play, PlayInfo{9, 0, "casat001", "31/G3.2-3"}},
        {RecordType::Play, PlayInfo{9, 0, "duraj001", "S7/L78D+.3-H"}},
        {RecordType::Play, PlayInfo{9, 0, "dever001", "DI.1-2"}},
        {RecordType::Play, PlayInfo{9, 0, "dever001", "W"}},
        {RecordType::Play, PlayInfo{9, 0, "brega001", "5/P15"}}
    };
}

std::optional<Record> StaticEventSource::Next() {
    if (currentIndex < records.size()) {
        return records[currentIndex++];
    }
    return std::nullopt;
}
