#include "EventSource.hpp"
#include "Records.hpp"
#include "Simulator.hpp"
#include "SimulatorObserver.hpp"
#include "StaticEventSource.hpp"
#include "chadwick/Game.hpp"
#include <filesystem>
#include <iostream>
#include <utility>
#include <vector>

auto main() -> int {
    std::cout << "Starting Chadwick example...\n";

    // NOLINTBEGIN(cppcoreguidelines-avoid-magic-numbers, readability-magic-numbers)
    std::vector<Record> records = {
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 1,
                          .team = 0,
                          .batter = "duraj001",
                          .pitchCount = "10",
                          .pitchSequence = "BX",
                          .text = "7/F7D"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 1,
                          .team = 0,
                          .batter = "dever001",
                          .pitchCount = "32",
                          .pitchSequence = "BBFSFF.BFB",
                          .text = "W"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 1,
                          .team = 0,
                          .batter = "brega001",
                          .pitchCount = "10",
                          .pitchSequence = "B.X",
                          .text = "S7/L78D+.1-2"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 1,
                          .team = 0,
                          .batter = "refsr001",
                          .pitchCount = "22",
                          .pitchSequence = "CFBBT",
                          .text = "K"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 1,
                          .team = 0,
                          .batter = "stort001",
                          .pitchCount = "02",
                          .pitchSequence = "CFS",
                          .text = "K"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 1,
                          .team = 1,
                          .batter = "westj002",
                          .pitchCount = "22",
                          .pitchSequence = "CBFBX",
                          .text = "S8/G6M"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 1,
                          .team = 1,
                          .batter = "rutsa001",
                          .pitchCount = "11",
                          .pitchSequence = "CBX",
                          .text = "S7/L7S.1-2"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 1,
                          .team = 1,
                          .batter = "oneit001",
                          .pitchCount = "22",
                          .pitchSequence = "CF*BB>X",
                          .text = "S7/G56.2-H;1-2"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 1,
                          .team = 1,
                          .batter = "mounr001",
                          .pitchCount = "01",
                          .pitchSequence = "*SX",
                          .text = "S7/L7LS.2-H;1-3(E7);B-2"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 1,
                          .team = 1,
                          .batter = "kjerh001",
                          .pitchCount = "12",
                          .pitchSequence = "SBSC",
                          .text = "K"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 1,
                          .team = 1,
                          .batter = "laurr001",
                          .pitchCount = "12",
                          .pitchSequence = "BFCS",
                          .text = "K"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 1,
                          .team = 1,
                          .batter = "mullc002",
                          .pitchCount = "20",
                          .pitchSequence = "BBX",
                          .text = "D8/L8D.3-H;2-H"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 1,
                          .team = 1,
                          .batter = "uriar001",
                          .pitchCount = "12",
                          .pitchSequence = "CFBS",
                          .text = "K"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 2,
                          .team = 0,
                          .batter = "campk002",
                          .pitchCount = "32",
                          .pitchSequence = "CBBBCB",
                          .text = "W"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 2,
                          .team = 0,
                          .batter = "gonzr003",
                          .pitchCount = "01",
                          .pitchSequence = "S1X",
                          .text = "S7/G56.1-2"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 2,
                          .team = 0,
                          .batter = "wongc001",
                          .pitchCount = "22",
                          .pitchSequence = "CBCBC",
                          .text = "K"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 2,
                          .team = 0,
                          .batter = "rafac001",
                          .pitchCount = "02",
                          .pitchSequence = "FSX",
                          .text = "53/G5S"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 2,
                          .team = 0,
                          .batter = "duraj001",
                          .pitchCount = "10",
                          .pitchSequence = "BX",
                          .text = "T8/F78XD+.2-H;1-H"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 2,
                          .team = 0,
                          .batter = "dever001",
                          .pitchCount = "22",
                          .pitchSequence = "FBFBT",
                          .text = "K"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 2,
                          .team = 1,
                          .batter = "hollj003",
                          .pitchCount = "00",
                          .pitchSequence = "X",
                          .text = "S8/G6+"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 2,
                          .team = 1,
                          .batter = "westj002",
                          .pitchCount = "11",
                          .pitchSequence = "CB>B",
                          .text = "CS2(24)"}},
        {.type = RecordType::Comment, .data = "$Orioles challenged (tag play), call on the field was upheld."},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 2,
                          .team = 1,
                          .batter = "westj002",
                          .pitchCount = "31",
                          .pitchSequence = "CB>B.BB",
                          .text = "W"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 2,
                          .team = 1,
                          .batter = "rutsa001",
                          .pitchCount = "11",
                          .pitchSequence = "CBX",
                          .text = "46(1)3/GDP/G4"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 3,
                          .team = 0,
                          .batter = "brega001",
                          .pitchCount = "32",
                          .pitchSequence = "CBBFBC",
                          .text = "K"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 3,
                          .team = 0,
                          .batter = "refsr001",
                          .pitchCount = "12",
                          .pitchSequence = "BC.SFX",
                          .text = "S7/L78"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 3,
                          .team = 0,
                          .batter = "stort001",
                          .pitchCount = "22",
                          .pitchSequence = "FBB1FX",
                          .text = "S9/L9LS.1-3;B-2(E9/TH)"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 3,
                          .team = 0,
                          .batter = "campk002",
                          .pitchCount = "12",
                          .pitchSequence = "FFF*BX",
                          .text = "43/G4MD.3-H;2-3"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 3,
                          .team = 0,
                          .batter = "gonzr003",
                          .pitchCount = "22",
                          .pitchSequence = "FBBCFF.C",
                          .text = "K"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 3,
                          .team = 1,
                          .batter = "oneit001",
                          .pitchCount = "01",
                          .pitchSequence = "CX",
                          .text = "S9/F9LS"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 3,
                          .team = 1,
                          .batter = "mounr001",
                          .pitchCount = "32",
                          .pitchSequence = "BBBCSB",
                          .text = "W.1-2"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 3,
                          .team = 1,
                          .batter = "kjerh001",
                          .pitchCount = "12",
                          .pitchSequence = "BC*SFC",
                          .text = "K"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 3,
                          .team = 1,
                          .batter = "laurr001",
                          .pitchCount = "10",
                          .pitchSequence = "BX",
                          .text = "64(1)3/GDP/G6"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 4,
                          .team = 0,
                          .batter = "wongc001",
                          .pitchCount = "31",
                          .pitchSequence = "BBFBX",
                          .text = "13/G15"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 4,
                          .team = 0,
                          .batter = "rafac001",
                          .pitchCount = "02",
                          .pitchSequence = "FSX",
                          .text = "53/G5S"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 4,
                          .team = 0,
                          .batter = "duraj001",
                          .pitchCount = "32",
                          .pitchSequence = "CBF.BBFX",
                          .text = "43/G34D"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 4,
                          .team = 1,
                          .batter = "mullc002",
                          .pitchCount = "00",
                          .pitchSequence = "X",
                          .text = "4/P4D"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 4,
                          .team = 1,
                          .batter = "uriar001",
                          .pitchCount = "22",
                          .pitchSequence = "CS.FBBFX",
                          .text = "S67/G56"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 4,
                          .team = 1,
                          .batter = "hollj003",
                          .pitchCount = "10",
                          .pitchSequence = "BX",
                          .text = "16(1)3/GDP/G1S"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 5,
                          .team = 0,
                          .batter = "dever001",
                          .pitchCount = "32",
                          .pitchSequence = "BFFFBBC",
                          .text = "K"}},
        {.type = RecordType::Play,
         .data =
             PlayInfo{
                 .inning = 5, .team = 0, .batter = "brega001", .pitchCount = "00", .pitchSequence = "", .text = "NP"}},
        {.type = RecordType::Substitution,
         .data = SubstitutionInfo{.playerId = "bowmm001", .name = "Matt Bowman", .team = 1, .slot = 0, .pos = 1}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 5,
                          .team = 0,
                          .batter = "brega001",
                          .pitchCount = "01",
                          .pitchSequence = ".CX",
                          .text = "8/F8"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 5,
                          .team = 0,
                          .batter = "refsr001",
                          .pitchCount = "01",
                          .pitchSequence = "SX",
                          .text = "S7/G56"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 5,
                          .team = 0,
                          .batter = "stort001",
                          .pitchCount = "01",
                          .pitchSequence = "F>B",
                          .text = "SB2"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 5,
                          .team = 0,
                          .batter = "stort001",
                          .pitchCount = "22",
                          .pitchSequence = "F>B.F.BS",
                          .text = "K"}},
        {.type = RecordType::Play,
         .data =
             PlayInfo{
                 .inning = 5, .team = 1, .batter = "westj002", .pitchCount = "00", .pitchSequence = "", .text = "NP"}},
        {.type = RecordType::Substitution,
         .data = SubstitutionInfo{.playerId = "whitg002", .name = "Garrett Whitlock", .team = 0, .slot = 0, .pos = 1}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 5,
                          .team = 1,
                          .batter = "westj002",
                          .pitchCount = "12",
                          .pitchSequence = ".BCCX",
                          .text = "53/G56"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 5,
                          .team = 1,
                          .batter = "rutsa001",
                          .pitchCount = "22",
                          .pitchSequence = "BCBC.*S",
                          .text = "K"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 5,
                          .team = 1,
                          .batter = "oneit001",
                          .pitchCount = "10",
                          .pitchSequence = "BX",
                          .text = "D8/L89XD+"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 5,
                          .team = 1,
                          .batter = "mounr001",
                          .pitchCount = "11",
                          .pitchSequence = "BCX",
                          .text = "9/F9D"}},
        {.type = RecordType::Play,
         .data =
             PlayInfo{
                 .inning = 6, .team = 0, .batter = "campk002", .pitchCount = "00", .pitchSequence = "", .text = "NP"}},
        {.type = RecordType::Substitution,
         .data =
             SubstitutionInfo{.playerId = "domis001", .name = "Seranthony Dominguez", .team = 1, .slot = 0, .pos = 1}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 6,
                          .team = 0,
                          .batter = "campk002",
                          .pitchCount = "22",
                          .pitchSequence = ".CBS.BC",
                          .text = "K"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 6,
                          .team = 0,
                          .batter = "gonzr003",
                          .pitchCount = "32",
                          .pitchSequence = "FBSBFBFX",
                          .text = "9/F89"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 6,
                          .team = 0,
                          .batter = "wongc001",
                          .pitchCount = "11",
                          .pitchSequence = "SBX",
                          .text = "4/L4D"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 6,
                          .team = 1,
                          .batter = "kjerh001",
                          .pitchCount = "11",
                          .pitchSequence = "CBX",
                          .text = "5/P56D"}},
        {.type = RecordType::Play,
         .data =
             PlayInfo{
                 .inning = 6, .team = 1, .batter = "laurr001", .pitchCount = "00", .pitchSequence = "", .text = "NP"}},
        {.type = RecordType::Substitution,
         .data = SubstitutionInfo{.playerId = "carld002", .name = "Dylan Carlson", .team = 1, .slot = 6, .pos = 11}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 6,
                          .team = 1,
                          .batter = "carld002",
                          .pitchCount = "22",
                          .pitchSequence = ".CBC.BFS",
                          .text = "K"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 6,
                          .team = 1,
                          .batter = "mullc002",
                          .pitchCount = "00",
                          .pitchSequence = "X",
                          .text = "31/G34"}},
        {.type = RecordType::Play,
         .data =
             PlayInfo{
                 .inning = 7, .team = 0, .batter = "rafac001", .pitchCount = "00", .pitchSequence = "", .text = "NP"}},
        {.type = RecordType::Substitution,
         .data = SubstitutionInfo{.playerId = "carld002", .name = "Dylan Carlson", .team = 1, .slot = 6, .pos = 9}},
        {.type = RecordType::Play,
         .data =
             PlayInfo{
                 .inning = 7, .team = 0, .batter = "rafac001", .pitchCount = "00", .pitchSequence = ".", .text = "NP"}},
        {.type = RecordType::Substitution,
         .data = SubstitutionInfo{.playerId = "akink001", .name = "Keegan Akin", .team = 1, .slot = 0, .pos = 1}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 7,
                          .team = 0,
                          .batter = "rafac001",
                          .pitchCount = "01",
                          .pitchSequence = "..CX",
                          .text = "9/F9LD"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 7,
                          .team = 0,
                          .batter = "duraj001",
                          .pitchCount = "02",
                          .pitchSequence = "CS.S",
                          .text = "K"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 7,
                          .team = 0,
                          .batter = "dever001",
                          .pitchCount = "22",
                          .pitchSequence = "SFBFBFF.S",
                          .text = "K"}},
        {.type = RecordType::Play,
         .data =
             PlayInfo{
                 .inning = 7, .team = 1, .batter = "uriar001", .pitchCount = "00", .pitchSequence = "", .text = "NP"}},
        {.type = RecordType::Substitution,
         .data = SubstitutionInfo{.playerId = "weisg001", .name = "Greg Weissert", .team = 0, .slot = 0, .pos = 1}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 7,
                          .team = 1,
                          .batter = "uriar001",
                          .pitchCount = "11",
                          .pitchSequence = ".BCX",
                          .text = "S7/L7LS"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 7,
                          .team = 1,
                          .batter = "hollj003",
                          .pitchCount = "32",
                          .pitchSequence = "S*BBBCC",
                          .text = "K"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 7,
                          .team = 1,
                          .batter = "westj002",
                          .pitchCount = "01",
                          .pitchSequence = "CX",
                          .text = "9/L9D"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 7,
                          .team = 1,
                          .batter = "rutsa001",
                          .pitchCount = "20",
                          .pitchSequence = "BBX",
                          .text = "9/F9LS"}},
        {.type = RecordType::Play,
         .data =
             PlayInfo{
                 .inning = 8, .team = 0, .batter = "brega001", .pitchCount = "00", .pitchSequence = "", .text = "NP"}},
        {.type = RecordType::Substitution,
         .data = SubstitutionInfo{.playerId = "canoy001", .name = "Yennier Cano", .team = 1, .slot = 0, .pos = 1}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 8,
                          .team = 0,
                          .batter = "brega001",
                          .pitchCount = "11",
                          .pitchSequence = ".BCX",
                          .text = "63/G6"}},
        {.type = RecordType::Play,
         .data =
             PlayInfo{
                 .inning = 8, .team = 0, .batter = "refsr001", .pitchCount = "00", .pitchSequence = "", .text = "NP"}},
        {.type = RecordType::Substitution,
         .data = SubstitutionInfo{.playerId = "abrew002", .name = "Wilyer Abreu", .team = 0, .slot = 4, .pos = 11}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 8,
                          .team = 0,
                          .batter = "abrew002",
                          .pitchCount = "01",
                          .pitchSequence = ".CX",
                          .text = "13/G4MS"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 8,
                          .team = 0,
                          .batter = "stort001",
                          .pitchCount = "12",
                          .pitchSequence = "CS.B*S",
                          .text = "K"}},
        {.type = RecordType::Play,
         .data =
             PlayInfo{
                 .inning = 8, .team = 1, .batter = "oneit001", .pitchCount = "00", .pitchSequence = "", .text = "NP"}},
        {.type = RecordType::Substitution,
         .data = SubstitutionInfo{.playerId = "abrew002", .name = "Wilyer Abreu", .team = 0, .slot = 4, .pos = 9}},
        {.type = RecordType::Play,
         .data =
             PlayInfo{
                 .inning = 8, .team = 1, .batter = "oneit001", .pitchCount = "00", .pitchSequence = ".", .text = "NP"}},
        {.type = RecordType::Substitution,
         .data = SubstitutionInfo{.playerId = "slatj002", .name = "Justin Slaten", .team = 0, .slot = 0, .pos = 1}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 8,
                          .team = 1,
                          .batter = "oneit001",
                          .pitchCount = "01",
                          .pitchSequence = "..FX",
                          .text = "S9/F89"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 8,
                          .team = 1,
                          .batter = "mounr001",
                          .pitchCount = "00",
                          .pitchSequence = "X",
                          .text = "S5/G6.1-3(E5/TH);B-2"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 8,
                          .team = 1,
                          .batter = "kjerh001",
                          .pitchCount = "10",
                          .pitchSequence = "BX",
                          .text = "S7/L7S.3-H;2-3"}},
        {.type = RecordType::Play,
         .data =
             PlayInfo{
                 .inning = 8, .team = 1, .batter = "carld002", .pitchCount = "00", .pitchSequence = "", .text = "NP"}},
        {.type = RecordType::Substitution,
         .data = SubstitutionInfo{.playerId = "matej003", .name = "Jorge Mateo", .team = 1, .slot = 5, .pos = 12}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 8,
                          .team = 1,
                          .batter = "carld002",
                          .pitchCount = "20",
                          .pitchSequence = ".BB>B",
                          .text = "SB2"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 8,
                          .team = 1,
                          .batter = "carld002",
                          .pitchCount = "30",
                          .pitchSequence = ".BB>B.*B",
                          .text = "W"}},
        {.type = RecordType::Play,
         .data =
             PlayInfo{
                 .inning = 8, .team = 1, .batter = "mullc002", .pitchCount = "00", .pitchSequence = "", .text = "NP"}},
        {.type = RecordType::Substitution,
         .data = SubstitutionInfo{.playerId = "crisc002", .name = "Cooper Criswell", .team = 0, .slot = 0, .pos = 1}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 8,
                          .team = 1,
                          .batter = "mullc002",
                          .pitchCount = "10",
                          .pitchSequence = ".BX",
                          .text = "S18/G4M.3-H;2-H;1-2"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 8,
                          .team = 1,
                          .batter = "uriar001",
                          .pitchCount = "01",
                          .pitchSequence = "CX",
                          .text = "54(1)/FO/G6.2-3;B-1"}},
        {.type = RecordType::Comment, .data = "$Umpire reviewed (play at 1st), call on the field was overturned."},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 8,
                          .team = 1,
                          .batter = "hollj003",
                          .pitchCount = "00",
                          .pitchSequence = "X",
                          .text = "S7/L7S.3-H;1-2"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 8,
                          .team = 1,
                          .batter = "westj002",
                          .pitchCount = "00",
                          .pitchSequence = "X",
                          .text = "4(1)/FO/G4M.2-3;B-1"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 8,
                          .team = 1,
                          .batter = "rutsa001",
                          .pitchCount = "21",
                          .pitchSequence = "B1BFX",
                          .text = "4/L34D"}},
        {.type = RecordType::Play,
         .data =
             PlayInfo{
                 .inning = 9, .team = 0, .batter = "campk002", .pitchCount = "00", .pitchSequence = ".", .text = "NP"}},
        {.type = RecordType::Substitution,
         .data = SubstitutionInfo{.playerId = "bautf001", .name = "Felix Bautista", .team = 1, .slot = 0, .pos = 1}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 9,
                          .team = 0,
                          .batter = "campk002",
                          .pitchCount = "32",
                          .pitchSequence = "..BFBS.B*B",
                          .text = "W"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 9,
                          .team = 0,
                          .batter = "gonzr003",
                          .pitchCount = "00",
                          .pitchSequence = "B",
                          .text = "WP.1-2"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 9,
                          .team = 0,
                          .batter = "gonzr003",
                          .pitchCount = "10",
                          .pitchSequence = "B.X",
                          .text = "D7/L7LD+.2-H"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 9,
                          .team = 0,
                          .batter = "wongc001",
                          .pitchCount = "00",
                          .pitchSequence = "X",
                          .text = "63/G6"}},
        {.type = RecordType::Play,
         .data =
             PlayInfo{
                 .inning = 9, .team = 0, .batter = "rafac001", .pitchCount = "00", .pitchSequence = "", .text = "NP"}},
        {.type = RecordType::Substitution,
         .data = SubstitutionInfo{.playerId = "casat001", .name = "Triston Casas", .team = 0, .slot = 9, .pos = 11}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 9,
                          .team = 0,
                          .batter = "casat001",
                          .pitchCount = "32",
                          .pitchSequence = ".BFS.*BFBX",
                          .text = "31/G3.2-3"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 9,
                          .team = 0,
                          .batter = "duraj001",
                          .pitchCount = "10",
                          .pitchSequence = "BX",
                          .text = "S7/L78D+.3-H"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 9,
                          .team = 0,
                          .batter = "dever001",
                          .pitchCount = "10",
                          .pitchSequence = "B>B",
                          .text = "DI.1-2"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 9,
                          .team = 0,
                          .batter = "dever001",
                          .pitchCount = "32",
                          .pitchSequence = "B>B.BCFB",
                          .text = "W"}},
        {.type = RecordType::Play,
         .data = PlayInfo{.inning = 9,
                          .team = 0,
                          .batter = "brega001",
                          .pitchCount = "10",
                          .pitchSequence = "BX",
                          .text = "5/P15"}}};
    // NOLINTEND(cppcoreguidelines-avoid-magic-numbers, readability-magic-numbers)

    StaticEventSource eventSource(std::move(records));
    SimulatorObserver observer;
    Simulator const simulator(&eventSource, &observer);

    std::vector<InfoRecord> const infoRecords = {{.key = "date", .value = "2025/03/31"},
                                                 {.key = "hometeam", .value = "BAL"},
                                                 {.key = "visteam", .value = "BOS"}};

    std::vector<StarterInfo> const starters = {
        {.id = "duraj001", .name = "Jarren Duran", .isHome = false, .battingOrder = 1, .position = 7},
        {.id = "dever001", .name = "Rafael Devers", .isHome = false, .battingOrder = 2, .position = 10},
        {.id = "brega001", .name = "Alex Bregman", .isHome = false, .battingOrder = 3, .position = 5},
        {.id = "refsr001", .name = "Rob Refsnyder", .isHome = false, .battingOrder = 4, .position = 9},
        {.id = "stort001", .name = "Trevor Story", .isHome = false, .battingOrder = 5, .position = 6},
        {.id = "campk002", .name = "Kristian Campbell", .isHome = false, .battingOrder = 6, .position = 4},
        {.id = "gonzr003", .name = "Romy Gonzalez", .isHome = false, .battingOrder = 7, .position = 3},
        {.id = "wongc001", .name = "Connor Wong", .isHome = false, .battingOrder = 8, .position = 2},
        {.id = "rafac001", .name = "Ceddanne Rafaela", .isHome = false, .battingOrder = 9, .position = 8},
        {.id = "newcs001", .name = "Sean Newcomb", .isHome = false, .battingOrder = 0, .position = 1},
        {.id = "westj002", .name = "Jordan Westburg", .isHome = true, .battingOrder = 1, .position = 4},
        {.id = "rutsa001", .name = "Adley Rutschman", .isHome = true, .battingOrder = 2, .position = 2},
        {.id = "oneit001", .name = "Tyler O'Neill", .isHome = true, .battingOrder = 3, .position = 7},
        {.id = "mounr001", .name = "Ryan Mountcastle", .isHome = true, .battingOrder = 4, .position = 3},
        {.id = "kjerh001", .name = "Heston Kjerstad", .isHome = true, .battingOrder = 5, .position = 10},
        {.id = "laurr001", .name = "Ramon Laureano", .isHome = true, .battingOrder = 6, .position = 9},
        {.id = "mullc002", .name = "Cedric Mullins", .isHome = true, .battingOrder = 7, .position = 8},
        {.id = "uriar001", .name = "Ramon Urias", .isHome = true, .battingOrder = 8, .position = 5},
        {.id = "hollj003", .name = "Jackson Holliday", .isHome = true, .battingOrder = 9, .position = 6},
        {.id = "povic001", .name = "Cade Povich", .isHome = true, .battingOrder = 0, .position = 1}};

    chadwick::Game game("BAL202503310", "2", infoRecords, starters);
    if (!game) {
        std::cerr << "Failed to create game\n";
        return 1;
    }

    simulator.SimulateGame(game);

    if (game.Write("game.evn")) {
        std::cout << "Game written to " << std::filesystem::current_path() << "/game.evn\n";
    } else {
        std::cerr << "Failed to open game.evn for writing\n";
    }

    return 0;
}